/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kwai_sod_NativeRun */

#ifndef _Included_com_kwai_sod_NativeRun
#define _Included_com_kwai_sod_NativeRun
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kwai_sod_NativeRun
 * Method:    callNative
 * Signature: ([BLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kwai_sod_NativeRun_callNative
  (JNIEnv *, jclass, jbyteArray, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
