#!/bin/bash

"$SPARK_HOME"/bin/spark-sql \
        --jars /Volumes/Workspace/blaze-init/spark-blaze-extension/target/spark-blaze-extension-1.0-SNAPSHOT.jar \
        --driver-java-options "-Djava.library.path=$JAVA_HOME:/Volumes/Workspace/blaze-init/blaze-rs/target/debug" \
        --conf spark.sql.extensions=org.apache.spark.sql.blaze.BlazeSparkSessionExtension \
        --conf spark.shuffle.manager=org.apache.spark.sql.blaze.execution.ArrowShuffleManager301 \
        --conf spark.sql.codegen.wholeStage=false \
        $@

