#!/bin/bash

"$SPARK_HOME"/bin/spark-sql \
        --jars /Volumes/Workspace/blaze-init/spark-auron-extension/target/spark-auron-extension-1.0-SNAPSHOT.jar \
        --driver-java-options "-Djava.library.path=$JAVA_HOME:/Volumes/Workspace/blaze-init/auron-rs/target/debug" \
        --conf spark.sql.extensions=org.apache.spark.sql.auron.AuronSparkSessionExtension \
        --conf spark.shuffle.manager=org.apache.spark.sql.auron.execution.ArrowShuffleManager301 \
        --conf spark.sql.codegen.wholeStage=false \
        $@

